### ISSUE TITLE
BackendConnector wrong interface

### ISSUE THREAD

**Issue by GrafZ3pp3lin** [GaiserJohannes/handycrab-android#1]
Im **BackendConnector** wird eine Solution erwartet, ich möchte aber nur den Text für die Solution übergeben.

`CompletableFuture<Barrier> addBarrierAsync(String title, double longitude, double latitude, String picture_base64, String description, String postcode, Solution solution);`

`CompletableFuture<Barrier> addSolutionAsync(ObjectId barrierID, Solution solution);`

**Comment by SchmidJoel** [comment]
erledigt
